#:schema node_modules/wrangler/config-schema.json
name = "dxd-cdn"
main = "src/index.js"
compatibility_date = "2024-12-05"
compatibility_flags = ["nodejs_compat"]

# Custom domain configuration
routes = [
    { pattern = "cdn.designxdevelop.com", custom_domain = true }
]

# Bind an R2 Bucket for CDN storage
[[r2_buckets]]
binding = "CDN_BUCKET"
bucket_name = "dxd-cdn"

# Secret for GitHub API access
# Add your GitHub token using: wrangler secret put GITHUB_TOKEN

# Secret for Sentry DSN
# Add your Sentry DSN using: wrangler secret put SENTRY_DSN

[vars]
ENVIRONMENT = "production"
# Add any other non-secret environment variables here
