#:schema node_modules/wrangler/config-schema.json
name = "dxd-cdn"
main = "src/index.js"
compatibility_date = "2024-12-05"
compatibility_flags = ["nodejs_compat"]

# Custom domain configuration
routes = [
    { pattern = "cdn.designxdevelop.com", custom_domain = true }
]

# R2 bucket configuration
[[r2_buckets]]
binding = "CDN_BUCKET"
bucket_name = "dxd-cdn"

# Environment variables
[vars]
ENVIRONMENT = "production"

[observability.logs]
enabled = true
invocation_logs = false